/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  darkMode: "class", // Enable class-based dark mode
  theme: {
    extend: {
      colors: {
        // Define CSS variables for themes
        background: "var(--background)",
        card: "var(--card)",
        navbar: "var(--navbar)",
        footer: "var(--footer)",
        sofwords: "var(--sofwords)",
        "sofwords-secondary": "var(--sofwords-secondary)",
        "sofwords-disabled": "var(--sofwords-disabled)",
        link: "var(--link)",
        "link-alt": "var(--link-alt)",
        "navbar-text": "var(--navbar-text)",
        "btn-primary": "var(--btn-primary)",
        "btn-primary-hover": "var(--btn-primary-hover)",
        "btn-secondary": "var(--btn-secondary)",
        "btn-secondary-hover": "var(--btn-secondary-hover)",
        "btn-disabled": "var(--btn-disabled)",
        "btn-text": "var(--btn-text)",
        input: "var(--input)",
        "input-border": "var(--input-border)",
        "input-placeholder": "var(--input-placeholder)",
        "input-focus": "var(--input-focus)",
        "input-error": "var(--input-error)",
        "nav-text": "var(--nav-text)",
        "nav-active": "var(--nav-active)",
        "nav-hover": "var(--nav-hover)",
        "card-border": "var(--card-border)",
        "card-title": "var(--card-title)",
        "card-subtext": "var(--card-subtext)",
        "cart-card": "var(--cart-card)",
        mborder: "var(--mborder)",
        cborder: "var(--cborder)",
        icon: "var(--icon)",
        "icon-alt": "var(--icon-alt)",
        accent: "var(--accent)",
        badge: "var(--badge)",
        success: "var(--success)",
        warning: "var(--warning)",
        error: "var(--error)",
        info: "var(--info)",
        divider: "var(--divider)",
        section: "var(--section)",
        "shadow-card": "var(--shadow-card)",
        "shadow-floating": "var(--shadow-floating)",
        "slider-shadow": "var(--slider-shadow)",
        "cart-card-buttonborder": "var(--cart-card-buttonborder)",
      },
      fontFamily: {
        sans: ["Merriweather", "serif"],
      },
    },
  },
  plugins: [],
};
