const productData = [
  {
    id: 1,
    name: "Dog Food - Dry 1",
    price: 11.25,
    image: "/products/food/DogFood_2.png",
    description: "Dog food item for dry needs.",
    animal: "dog",
    category: "food",
    subcategory: "Dry",
    SKU: "FD1001",
    brand: "HealthyPaws",
    rating: 4.5,
    salesVolume: 127,
  },
  {
    id: 2,
    name: "Dog Food - Dry 2",
    price: 12.5,
    image: "/products/food/DogFood_2.png",
    description: "Dog food item for dry needs.",
    animal: "dog",
    category: "food",
    subcategory: "Dry",
    SKU: "FD1002",
    brand: "Claw Haven",
    rating: 3.0,
    salesVolume: 84,
  },
  {
    id: 3,
    name: "Dog Food - Dry 3",
    price: 13.75,
    image: "/products/food/DogFood_2.png",
    description: "Dog food item for dry needs.",
    animal: "dog",
    category: "food",
    subcategory: "Dry",
    SKU: "FD1003",
    brand: "FeatherFun",
    rating: 4.0,
    salesVolume: 156,
  },
  {
    id: 4,
    name: "Dog Food - Wet 1",
    price: 15.0,
    image: "/products/food/DogFood_1.png",
    description: "Dog food item for wet needs.",
    animal: "dog",
    category: "food",
    subcategory: "Wet",
    SKU: "FD1004",
    brand: "Tug Time",
    rating: 2.5,
    salesVolume: 67,
  },
  {
    id: 5,
    name: "Dog Food - Wet 2",
    price: 16.25,
    image: "/products/food/DogFood_1.png",
    description: "Dog food item for wet needs.",
    animal: "dog",
    category: "food",
    subcategory: "Wet",
    SKU: "FD1005",
    brand: "PlayPaws",
    rating: 5.0,
    salesVolume: 198,
  },
  {
    id: 6,
    name: "Dog Food - Wet 3",
    price: 17.5,
    image: "/products/food/DogFood_1.png",
    description: "Dog food item for wet needs.",
    animal: "dog",
    category: "food",
    subcategory: "Wet",
    SKU: "FD1006",
    brand: "Natural Branch",
    rating: 3.5,
    salesVolume: 112,
  },
  {
    id: 7,
    name: "Dog Food - Grain-Free 1",
    price: 18.75,
    image: "/products/food/DogFood_3.png",
    description: "Dog food item for grain-free needs.",
    animal: "dog",
    category: "food",
    subcategory: "Grain-Free",
    SKU: "FD1007",
    brand: "Fetch Masters",
    rating: 4.0,
    salesVolume: 145,
  },
  {
    id: 8,
    name: "Dog Food - Grain-Free 2",
    price: 20.0,
    image: "/products/food/DogFood_3.png",
    description: "Dog food item for grain-free needs.",
    animal: "dog",
    category: "food",
    subcategory: "Grain-Free",
    SKU: "FD1008",
    brand: "WhiskerPlay",
    rating: 2.0,
    salesVolume: 42,
  },
  {
    id: 9,
    name: "Dog Food - Grain-Free 3",
    price: 21.25,
    image: "/products/food/DogFood_3.png",
    description: "Dog food item for grain-free needs.",
    animal: "dog",
    category: "food",
    subcategory: "Grain-Free",
    SKU: "FD1009",
    brand: "HealthyPaws",
    rating: 4.5,
    salesVolume: 176,
  },
  {
    id: 10,
    name: "Dog Food - Puppy 1",
    price: 22.5,
    image: "/products/food/DogFood_Puppy.png",
    description: "Dog food item for puppy needs.",
    animal: "dog",
    category: "food",
    subcategory: "Puppy",
    SKU: "FD1010",
    brand: "Claw Haven",
    rating: 3.5,
    salesVolume: 93,
  },
  {
    id: 11,
    name: "Dog Food - Puppy 2",
    price: 23.75,
    image: "/products/food/DogFood_Puppy.png",
    description: "Dog food item for puppy needs.",
    animal: "dog",
    category: "food",
    subcategory: "Puppy",
    SKU: "FD1011",
    brand: "FeatherFun",
    rating: 5.0,
    salesVolume: 204,
  },
  {
    id: 12,
    name: "Dog Food - Puppy 3",
    price: 25.0,
    image: "/products/food/DogFood_Puppy.png",
    description: "Dog food item for puppy needs.",
    animal: "dog",
    category: "food",
    subcategory: "Puppy",
    SKU: "FD1012",
    brand: "Tug Time",
    rating: 3.0,
    salesVolume: 78,
  },
  {
    id: 13,
    name: "Dog Food - Senior 1",
    price: 26.25,
    image: "/products/food/DogFood_Senior.png",
    description: "Dog food item for senior needs.",
    animal: "dog",
    category: "food",
    subcategory: "Senior",
    SKU: "FD1013",
    brand: "PlayPaws",
    rating: 4.0,
    salesVolume: 134,
  },
  {
    id: 14,
    name: "Dog Food - Senior 2",
    price: 27.5,
    image: "/products/food/DogFood_Senior.png",
    description: "Dog food item for senior needs.",
    animal: "dog",
    category: "food",
    subcategory: "Senior",
    SKU: "FD1014",
    brand: "Natural Branch",
    rating: 2.5,
    salesVolume: 56,
  },
  {
    id: 15,
    name: "Dog Food - Senior 3",
    price: 28.75,
    image: "/products/food/DogFood_Senior.png",
    description: "Dog food item for senior needs.",
    animal: "dog",
    category: "food",
    subcategory: "Senior",
    SKU: "FD1015",
    brand: "Fetch Masters",
    rating: 4.5,
    salesVolume: 167,
  },
  {
    id: 16,
    name: "Cat Food - Dry 1",
    price: 30.0,
    image: "/products/food/CatFood_2.png",
    description: "Cat food item for dry needs.",
    animal: "cat",
    category: "food",
    subcategory: "Dry",
    SKU: "FC1001",
    brand: "WhiskerPlay",
    rating: 3.5,
    salesVolume: 118,
  },
  {
    id: 17,
    name: "Cat Food - Dry 2",
    price: 31.25,
    image: "/products/food/CatFood_2.png",
    description: "Cat food item for dry needs.",
    animal: "cat",
    category: "food",
    subcategory: "Dry",
    SKU: "FC1002",
    brand: "HealthyPaws",
    rating: 4.0,
    salesVolume: 142,
  },
  {
    id: 18,
    name: "Cat Food - Dry 3",
    price: 32.5,
    image: "/products/food/CatFood_2.png",
    description: "Cat food item for dry needs.",
    animal: "cat",
    category: "food",
    subcategory: "Dry",
    SKU: "FC1003",
    brand: "Claw Haven",
    rating: 2.0,
    salesVolume: 39,
  },
  {
    id: 19,
    name: "Cat Food - Wet 1",
    price: 33.75,
    image: "/products/food/CatFood_1.png",
    description: "Cat food item for wet needs.",
    animal: "cat",
    category: "food",
    subcategory: "Wet",
    SKU: "FC1004",
    brand: "FeatherFun",
    rating: 5.0,
    salesVolume: 215,
  },
  {
    id: 20,
    name: "Cat Food - Wet 2",
    price: 10.0,
    image: "/products/food/CatFood_1.png",
    description: "Cat food item for wet needs.",
    animal: "cat",
    category: "food",
    subcategory: "Wet",
    SKU: "FC1005",
    brand: "Tug Time",
    rating: 3.0,
    salesVolume: 89,
  },
  {
    id: 21,
    name: "Cat Food - Wet 3",
    price: 11.25,
    image: "/products/food/CatFood_3.png",
    description: "Cat food item for wet needs.",
    animal: "cat",
    category: "food",
    subcategory: "Wet",
    SKU: "FC1006",
    brand: "PlayPaws",
    rating: 4.5,
    salesVolume: 183,
  },
  {
    id: 22,
    name: "Cat Food - Grain-Free 1",
    price: 12.5,
    image: "/products/food/CatFood_3.png",
    description: "Cat food item for grain-free needs.",
    animal: "cat",
    category: "food",
    subcategory: "Grain-Free",
    SKU: "FC1007",
    brand: "Natural Branch",
    rating: 3.5,
    salesVolume: 107,
  },
  {
    id: 23,
    name: "Cat Food - Grain-Free 2",
    price: 13.75,
    image: "/products/food/CatFood_3.png",
    description: "Cat food item for grain-free needs.",
    animal: "cat",
    category: "food",
    subcategory: "Grain-Free",
    SKU: "FC1008",
    brand: "Fetch Masters",
    rating: 2.5,
    salesVolume: 61,
  },
  {
    id: 24,
    name: "Cat Food - Grain-Free 3",
    price: 15.0,
    image: "/products/food/CatFood_3.png",
    description: "Cat food item for grain-free needs.",
    animal: "cat",
    category: "food",
    subcategory: "Grain-Free",
    SKU: "FC1009",
    brand: "WhiskerPlay",
    rating: 4.0,
    salesVolume: 138,
  },
  {
    id: 25,
    name: "Cat Food - Kitten 1",
    price: 16.25,
    image: "/products/food/CatFood_Kitty.png",
    description: "Cat food item for kitten needs.",
    animal: "cat",
    category: "food",
    subcategory: "Kitten",
    SKU: "FC1010",
    brand: "HealthyPaws",
    rating: 4.5,
    salesVolume: 192,
  },
  {
    id: 26,
    name: "Cat Food - Kitten 2",
    price: 17.5,
    image: "/products/food/CatFood_Kitty.png",
    description: "Cat food item for kitten needs.",
    animal: "cat",
    category: "food",
    subcategory: "Kitten",
    SKU: "FC1011",
    brand: "Claw Haven",
    rating: 3.0,
    salesVolume: 82,
  },
  {
    id: 27,
    name: "Cat Food - Kitten 3",
    price: 18.75,
    image: "/products/food/CatFood_Kitty.png",
    description: "Cat food item for kitten needs.",
    animal: "cat",
    category: "food",
    subcategory: "Kitten",
    SKU: "FC1012",
    brand: "FeatherFun",
    rating: 5.0,
    salesVolume: 221,
  },
  {
    id: 28,
    name: "Cat Food - Senior 1",
    price: 20.0,
    image: "/products/food/CatFood_Senior.png",
    description: "Cat food item for senior needs.",
    animal: "cat",
    category: "food",
    subcategory: "Senior",
    SKU: "FC1013",
    brand: "Tug Time",
    rating: 3.5,
    salesVolume: 98,
  },
  {
    id: 29,
    name: "Cat Food - Senior 2",
    price: 21.25,
    image: "/products/food/CatFood_Senior.png",
    description: "Cat food item for senior needs.",
    animal: "cat",
    category: "food",
    subcategory: "Senior",
    SKU: "FC1014",
    brand: "PlayPaws",
    rating: 4.0,
    salesVolume: 126,
  },
  {
    id: 30,
    name: "Cat Food - Senior 3",
    price: 22.5,
    image: "/products/food/CatFood_Senior.png",
    description: "Cat food item for senior needs.",
    animal: "cat",
    category: "food",
    subcategory: "Senior",
    SKU: "FC1015",
    brand: "Natural Branch",
    rating: 2.0,
    salesVolume: 47,
  },
  {
    id: 31,
    name: "Bird Food - Seeds 1",
    price: 23.75,
    image: "/products/food/BirdFood_1.png",
    description: "Bird food item for seeds needs.",
    animal: "bird",
    category: "food",
    subcategory: "Seeds",
    SKU: "FB1001",
    brand: "Fetch Masters",
    rating: 4.5,
    salesVolume: 174,
  },
  {
    id: 32,
    name: "Bird Food - Seeds 2",
    price: 25.0,
    image: "/products/food/BirdFood_1.png",
    description: "Bird food item for seeds needs.",
    animal: "bird",
    category: "food",
    subcategory: "Seeds",
    SKU: "FB1002",
    brand: "WhiskerPlay",
    rating: 3.0,
    salesVolume: 76,
  },
  {
    id: 33,
    name: "Bird Food - Seeds 3",
    price: 26.25,
    image: "/products/food/BirdFood_1.png",
    description: "Bird food item for seeds needs.",
    animal: "bird",
    category: "food",
    subcategory: "Seeds",
    SKU: "FB1003",
    brand: "HealthyPaws",
    rating: 4.0,
    salesVolume: 131,
  },
  {
    id: 34,
    name: "Bird Food - Pellets 1",
    price: 27.5,
    image: "/products/food/BirdFood_2.png",
    description: "Bird food item for pellets needs.",
    animal: "bird",
    category: "food",
    subcategory: "Pellets",
    SKU: "FB1004",
    brand: "Claw Haven",
    rating: 2.5,
    salesVolume: 58,
  },
  {
    id: 35,
    name: "Bird Food - Pellets 2",
    price: 28.75,
    image: "/products/food/BirdFood_2.png",
    description: "Bird food item for pellets needs.",
    animal: "bird",
    category: "food",
    subcategory: "Pellets",
    SKU: "FB1005",
    brand: "FeatherFun",
    rating: 5.0,
    salesVolume: 208,
  },
  {
    id: 36,
    name: "Bird Food - Pellets 3",
    price: 30.0,
    image: "/products/food/BirdFood_2.png",
    description: "Bird food item for pellets needs.",
    animal: "bird",
    category: "food",
    subcategory: "Pellets",
    SKU: "FB1006",
    brand: "Tug Time",
    rating: 3.5,
    salesVolume: 104,
  },
  {
    id: 37,
    name: "Bird Food - Treat Mixes 1",
    price: 31.25,
    image: "/products/food/BirdFood_3.png",
    description: "Bird food item for treat mixes needs.",
    animal: "bird",
    category: "food",
    subcategory: "Treat Mixes",
    SKU: "FB1007",
    brand: "PlayPaws",
    rating: 4.0,
    salesVolume: 149,
  },
  {
    id: 38,
    name: "Bird Food - Treat Mixes 2",
    price: 32.5,
    image: "/products/food/BirdFood_3.png",
    description: "Bird food item for treat mixes needs.",
    animal: "bird",
    category: "food",
    subcategory: "Treat Mixes",
    SKU: "FB1008",
    brand: "Natural Branch",
    rating: 2.0,
    salesVolume: 35,
  },
  {
    id: 39,
    name: "Bird Food - Treat Mixes 3",
    price: 33.75,
    image: "/products/food/BirdFood_3.png",
    description: "Bird food item for treat mixes needs.",
    animal: "bird",
    category: "food",
    subcategory: "Treat Mixes",
    SKU: "FB1009",
    brand: "Fetch Masters",
    rating: 4.5,
    salesVolume: 187,
  },
  {
    id: 40,
    name: "Bird Food - Nutritional Supplements 1",
    price: 10.0,
    image: "/products/food/BirdFood_4.png",
    description: "Bird food item for nutritional supplements needs.",
    animal: "bird",
    category: "food",
    subcategory: "Nutritional Supplements",
    SKU: "FB1010",
    brand: "WhiskerPlay",
    rating: 3.0,
    salesVolume: 71,
  },
  {
    id: 41,
    name: "Bird Food - Nutritional Supplements 2",
    price: 11.25,
    image: "/products/food/BirdFood_4.png",
    description: "Bird food item for nutritional supplements needs.",
    animal: "bird",
    category: "food",
    subcategory: "Nutritional Supplements",
    SKU: "FB1011",
    brand: "HealthyPaws",
    rating: 4.0,
    salesVolume: 123,
  },
  {
    id: 42,
    name: "Bird Food - Nutritional Supplements 3",
    price: 12.5,
    image: "/products/food/BirdFood_4.png",
    description: "Bird food item for nutritional supplements needs.",
    animal: "bird",
    category: "food",
    subcategory: "Nutritional Supplements",
    SKU: "FB1012",
    brand: "Claw Haven",
    rating: 2.5,
    salesVolume: 52,
  },
  {
    id: 43,
    name: "Dog Accessories - Collars 1",
    price: 13.75,
    image: "/products/empty.png",
    description: "Dog accessories item for collars needs.",
    animal: "dog",
    category: "accessories",
    subcategory: "Collars",
    SKU: "AD1001",
    brand: "FeatherFun",
    rating: 4.5,
    salesVolume: 169,
  },
  {
    id: 44,
    name: "Dog Accessories - Collars 2",
    price: 15.0,
    image: "/products/empty.png",
    description: "Dog accessories item for collars needs.",
    animal: "dog",
    category: "accessories",
    subcategory: "Collars",
    SKU: "AD1002",
    brand: "Tug Time",
    rating: 3.0,
    salesVolume: 87,
  },
  {
    id: 45,
    name: "Dog Accessories - Collars 3",
    price: 16.25,
    image: "/products/empty.png",
    description: "Dog accessories item for collars needs.",
    animal: "dog",
    category: "accessories",
    subcategory: "Collars",
    SKU: "AD1003",
    brand: "PlayPaws",
    rating: 4.0,
    salesVolume: 135,
  },
  {
    id: 46,
    name: "Dog Accessories - Leashes 1",
    price: 17.5,
    image: "/products/empty.png",
    description: "Dog accessories item for leashes needs.",
    animal: "dog",
    category: "accessories",
    subcategory: "Leashes",
    SKU: "AD1004",
    brand: "Natural Branch",
    rating: 2.5,
    salesVolume: 63,
  },
  {
    id: 47,
    name: "Dog Accessories - Leashes 2",
    price: 18.75,
    image: "/products/empty.png",
    description: "Dog accessories item for leashes needs.",
    animal: "dog",
    category: "accessories",
    subcategory: "Leashes",
    SKU: "AD1005",
    brand: "Fetch Masters",
    rating: 5.0,
    salesVolume: 196,
  },
  {
    id: 48,
    name: "Dog Accessories - Leashes 3",
    price: 20.0,
    image: "/products/empty.png",
    description: "Dog accessories item for leashes needs.",
    animal: "dog",
    category: "accessories",
    subcategory: "Leashes",
    SKU: "AD1006",
    brand: "WhiskerPlay",
    rating: 3.5,
    salesVolume: 109,
  },
  {
    id: 49,
    name: "Dog Accessories - Harnesses 1",
    price: 21.25,
    image: "/products/empty.png",
    description: "Dog accessories item for harnesses needs.",
    animal: "dog",
    category: "accessories",
    subcategory: "Harnesses",
    SKU: "AD1007",
    brand: "HealthyPaws",
    rating: 4.0,
    salesVolume: 141,
  },
  {
    id: 50,
    name: "Dog Accessories - Harnesses 2",
    price: 22.5,
    image: "/products/empty.png",
    description: "Dog accessories item for harnesses needs.",
    animal: "dog",
    category: "accessories",
    subcategory: "Harnesses",
    SKU: "AD1008",
    brand: "Claw Haven",
    rating: 2.0,
    salesVolume: 44,
  },
  {
    id: 51,
    name: "Dog Accessories - Harnesses 3",
    price: 23.75,
    image: "/products/empty.png",
    description: "Dog accessories item for harnesses needs.",
    animal: "dog",
    category: "accessories",
    subcategory: "Harnesses",
    SKU: "AD1009",
    brand: "FeatherFun",
    rating: 4.5,
    salesVolume: 178,
  },
  {
    id: 52,
    name: "Dog Accessories - Bowls 1",
    price: 25.0,
    image: "/products/empty.png",
    description: "Dog accessories item for bowls needs.",
    animal: "dog",
    category: "accessories",
    subcategory: "Bowls",
    SKU: "AD1010",
    brand: "Tug Time",
    rating: 3.0,
    salesVolume: 79,
  },
  {
    id: 53,
    name: "Dog Accessories - Bowls 2",
    price: 26.25,
    image: "/products/empty.png",
    description: "Dog accessories item for bowls needs.",
    animal: "dog",
    category: "accessories",
    subcategory: "Bowls",
    SKU: "AD1011",
    brand: "PlayPaws",
    rating: 4.0,
    salesVolume: 128,
  },
  {
    id: 54,
    name: "Dog Accessories - Bowls 3",
    price: 27.5,
    image: "/products/empty.png",
    description: "Dog accessories item for bowls needs.",
    animal: "dog",
    category: "accessories",
    subcategory: "Bowls",
    SKU: "AD1012",
    brand: "Natural Branch",
    rating: 2.5,
    salesVolume: 55,
  },
  {
    id: 55,
    name: "Dog Accessories - Beds 1",
    price: 28.75,
    image: "/products/empty.png",
    description: "Dog accessories item for beds needs.",
    animal: "dog",
    category: "accessories",
    subcategory: "Beds",
    SKU: "AD1013",
    brand: "Fetch Masters",
    rating: 5.0,
    salesVolume: 212,
  },
  {
    id: 56,
    name: "Dog Accessories - Beds 2",
    price: 30.0,
    image: "/products/empty.png",
    description: "Dog accessories item for beds needs.",
    animal: "dog",
    category: "accessories",
    subcategory: "Beds",
    SKU: "AD1014",
    brand: "WhiskerPlay",
    rating: 3.5,
    salesVolume: 97,
  },
  {
    id: 57,
    name: "Dog Accessories - Beds 3",
    price: 31.25,
    image: "/products/empty.png",
    description: "Dog accessories item for beds needs.",
    animal: "dog",
    category: "accessories",
    subcategory: "Beds",
    SKU: "AD1015",
    brand: "HealthyPaws",
    rating: 4.0,
    salesVolume: 132,
  },
  {
    id: 58,
    name: "Cat Accessories - Collars 1",
    price: 32.5,
    image: "/products/empty.png",
    description: "Cat accessories item for collars needs.",
    animal: "cat",
    category: "accessories",
    subcategory: "Collars",
    SKU: "AC1001",
    brand: "Claw Haven",
    rating: 2.0,
    salesVolume: 41,
  },
  {
    id: 59,
    name: "Cat Accessories - Collars 2",
    price: 33.75,
    image: "/products/empty.png",
    description: "Cat accessories item for collars needs.",
    animal: "cat",
    category: "accessories",
    subcategory: "Collars",
    SKU: "AC1002",
    brand: "FeatherFun",
    rating: 4.5,
    salesVolume: 185,
  },
  {
    id: 60,
    name: "Cat Accessories - Collars 3",
    price: 10.0,
    image: "/products/empty.png",
    description: "Cat accessories item for collars needs.",
    animal: "cat",
    category: "accessories",
    subcategory: "Collars",
    SKU: "AC1003",
    brand: "Tug Time",
    rating: 3.0,
    salesVolume: 73,
  },
  {
    id: 61,
    name: "Cat Accessories - Scratching Posts 1",
    price: 11.25,
    image: "/products/empty.png",
    description: "Cat accessories item for scratching posts needs.",
    animal: "cat",
    category: "accessories",
    subcategory: "Scratching Posts",
    SKU: "AC1004",
    brand: "PlayPaws",
    rating: 4.0,
    salesVolume: 139,
  },
  {
    id: 62,
    name: "Cat Accessories - Scratching Posts 2",
    price: 12.5,
    image: "/products/empty.png",
    description: "Cat accessories item for scratching posts needs.",
    animal: "cat",
    category: "accessories",
    subcategory: "Scratching Posts",
    SKU: "AC1005",
    brand: "Natural Branch",
    rating: 2.5,
    salesVolume: 59,
  },
  {
    id: 63,
    name: "Cat Accessories - Scratching Posts 3",
    price: 13.75,
    image: "/products/empty.png",
    description: "Cat accessories item for scratching posts needs.",
    animal: "cat",
    category: "accessories",
    subcategory: "Scratching Posts",
    SKU: "AC1006",
    brand: "Fetch Masters",
    rating: 5.0,
    salesVolume: 203,
  },
  {
    id: 64,
    name: "Cat Accessories - Litter Boxes 1",
    price: 15.0,
    image: "/products/empty.png",
    description: "Cat accessories item for litter boxes needs.",
    animal: "cat",
    category: "accessories",
    subcategory: "Litter Boxes",
    SKU: "AC1007",
    brand: "WhiskerPlay",
    rating: 3.5,
    salesVolume: 106,
  },
  {
    id: 65,
    name: "Cat Accessories - Litter Boxes 2",
    price: 16.25,
    image: "/products/empty.png",
    description: "Cat accessories item for litter boxes needs.",
    animal: "cat",
    category: "accessories",
    subcategory: "Litter Boxes",
    SKU: "AC1008",
    brand: "HealthyPaws",
    rating: 4.0,
    salesVolume: 124,
  },
  {
    id: 66,
    name: "Cat Accessories - Litter Boxes 3",
    price: 17.5,
    image: "/products/empty.png",
    description: "Cat accessories item for litter boxes needs.",
    animal: "cat",
    category: "accessories",
    subcategory: "Litter Boxes",
    SKU: "AC1009",
    brand: "Claw Haven",
    rating: 2.0,
    salesVolume: 38,
  },
  {
    id: 67,
    name: "Cat Accessories - Bowls 1",
    price: 18.75,
    image: "/products/empty.png",
    description: "Cat accessories item for bowls needs.",
    animal: "cat",
    category: "accessories",
    subcategory: "Bowls",
    SKU: "AC1010",
    brand: "FeatherFun",
    rating: 4.5,
    salesVolume: 179,
  },
  {
    id: 68,
    name: "Cat Accessories - Bowls 2",
    price: 20.0,
    image: "/products/empty.png",
    description: "Cat accessories item for bowls needs.",
    animal: "cat",
    category: "accessories",
    subcategory: "Bowls",
    SKU: "AC1011",
    brand: "Tug Time",
    rating: 3.0,
    salesVolume: 81,
  },
  {
    id: 69,
    name: "Cat Accessories - Bowls 3",
    price: 21.25,
    image: "/products/empty.png",
    description: "Cat accessories item for bowls needs.",
    animal: "cat",
    category: "accessories",
    subcategory: "Bowls",
    SKU: "AC1012",
    brand: "PlayPaws",
    rating: 4.0,
    salesVolume: 137,
  },
  {
    id: 70,
    name: "Cat Accessories - Beds 1",
    price: 22.5,
    image: "/products/empty.png",
    description: "Cat accessories item for beds needs.",
    animal: "cat",
    category: "accessories",
    subcategory: "Beds",
    SKU: "AC1013",
    brand: "Natural Branch",
    rating: 2.5,
    salesVolume: 54,
  },
  {
    id: 71,
    name: "Cat Accessories - Beds 2",
    price: 23.75,
    image: "/products/empty.png",
    description: "Cat accessories item for beds needs.",
    animal: "cat",
    category: "accessories",
    subcategory: "Beds",
    SKU: "AC1014",
    brand: "Fetch Masters",
    rating: 5.0,
    salesVolume: 217,
  },
  {
    id: 72,
    name: "Cat Accessories - Beds 3",
    price: 25.0,
    image: "/products/empty.png",
    description: "Cat accessories item for beds needs.",
    animal: "cat",
    category: "accessories",
    subcategory: "Beds",
    SKU: "AC1015",
    brand: "WhiskerPlay",
    rating: 3.5,
    salesVolume: 101,
  },
  {
    id: 73,
    name: "Bird Accessories - Cages 1",
    price: 26.25,
    image: "/products/empty.png",
    description: "Bird accessories item for cages needs.",
    animal: "bird",
    category: "accessories",
    subcategory: "Cages",
    SKU: "AB1001",
    brand: "HealthyPaws",
    rating: 4.0,
    salesVolume: 143,
  },
  {
    id: 74,
    name: "Bird Accessories - Cages 2",
    price: 27.5,
    image: "/products/empty.png",
    description: "Bird accessories item for cages needs.",
    animal: "bird",
    category: "accessories",
    subcategory: "Cages",
    SKU: "AB1002",
    brand: "Claw Haven",
    rating: 2.0,
    salesVolume: 36,
  },
  {
    id: 75,
    name: "Bird Accessories - Cages 3",
    price: 28.75,
    image: "/products/empty.png",
    description: "Bird accessories item for cages needs.",
    animal: "bird",
    category: "accessories",
    subcategory: "Cages",
    SKU: "AB1003",
    brand: "FeatherFun",
    rating: 4.5,
    salesVolume: 188,
  },
  {
    id: 76,
    name: "Bird Accessories - Perches 1",
    price: 30.0,
    image: "/products/empty.png",
    description: "Bird accessories item for perches needs.",
    animal: "bird",
    category: "accessories",
    subcategory: "Perches",
    SKU: "AB1004",
    brand: "Tug Time",
    rating: 3.0,
    salesVolume: 77,
  },
  {
    id: 77,
    name: "Bird Accessories - Perches 2",
    price: 31.25,
    image: "/products/empty.png",
    description: "Bird accessories item for perches needs.",
    animal: "bird",
    category: "accessories",
    subcategory: "Perches",
    SKU: "AB1005",
    brand: "PlayPaws",
    rating: 4.0,
    salesVolume: 129,
  },
  {
    id: 78,
    name: "Bird Accessories - Perches 3",
    price: 32.5,
    image: "/products/empty.png",
    description: "Bird accessories item for perches needs.",
    animal: "bird",
    category: "accessories",
    subcategory: "Perches",
    SKU: "AB1006",
    brand: "Natural Branch",
    rating: 2.5,
    salesVolume: 57,
  },
  {
    id: 79,
    name: "Bird Accessories - Feeders 1",
    price: 33.75,
    image: "/products/empty.png",
    description: "Bird accessories item for feeders needs.",
    animal: "bird",
    category: "accessories",
    subcategory: "Feeders",
    SKU: "AB1007",
    brand: "Fetch Masters",
    rating: 5.0,
    salesVolume: 199,
  },
  {
    id: 80,
    name: "Bird Accessories - Feeders 2",
    price: 10.0,
    image: "/products/empty.png",
    description: "Bird accessories item for feeders needs.",
    animal: "bird",
    category: "accessories",
    subcategory: "Feeders",
    SKU: "AB1008",
    brand: "WhiskerPlay",
    rating: 3.5,
    salesVolume: 108,
  },
  {
    id: 81,
    name: "Bird Accessories - Feeders 3",
    price: 11.25,
    image: "/products/empty.png",
    description: "Bird accessories item for feeders needs.",
    animal: "bird",
    category: "accessories",
    subcategory: "Feeders",
    SKU: "AB1009",
    brand: "HealthyPaws",
    rating: 4.0,
    salesVolume: 133,
  },
  {
    id: 82,
    name: "Bird Accessories - Nesting Boxes 1",
    price: 12.5,
    image: "/products/empty.png",
    description: "Bird accessories item for nesting boxes needs.",
    animal: "bird",
    category: "accessories",
    subcategory: "Nesting Boxes",
    SKU: "AB1010",
    brand: "Claw Haven",
    rating: 2.0,
    salesVolume: 43,
  },
  {
    id: 83,
    name: "Bird Accessories - Nesting Boxes 2",
    price: 13.75,
    image: "/products/empty.png",
    description: "Bird accessories item for nesting boxes needs.",
    animal: "bird",
    category: "accessories",
    subcategory: "Nesting Boxes",
    SKU: "AB1011",
    brand: "FeatherFun",
    rating: 4.5,
    salesVolume: 181,
  },
  {
    id: 84,
    name: "Bird Accessories - Nesting Boxes 3",
    price: 15.0,
    image: "/products/empty.png",
    description: "Bird accessories item for nesting boxes needs.",
    animal: "bird",
    category: "accessories",
    subcategory: "Nesting Boxes",
    SKU: "AB1012",
    brand: "Tug Time",
    rating: 3.0,
    salesVolume: 85,
  },
  {
    id: 85,
    name: "Bird Accessories - Play Gyms 1",
    price: 16.25,
    image: "/products/empty.png",
    description: "Bird accessories item for play gyms needs.",
    animal: "bird",
    category: "accessories",
    subcategory: "Play Gyms",
    SKU: "AB1013",
    brand: "PlayPaws",
    rating: 4.0,
    salesVolume: 136,
  },
  {
    id: 86,
    name: "Bird Accessories - Play Gyms 2",
    price: 17.5,
    image: "/products/empty.png",
    description: "Bird accessories item for play gyms needs.",
    animal: "bird",
    category: "accessories",
    subcategory: "Play Gyms",
    SKU: "AB1014",
    brand: "Natural Branch",
    rating: 2.5,
    salesVolume: 62,
  },
  {
    id: 87,
    name: "Bird Accessories - Play Gyms 3",
    price: 18.75,
    image: "/products/empty.png",
    description: "Bird accessories item for play gyms needs.",
    animal: "bird",
    category: "accessories",
    subcategory: "Play Gyms",
    SKU: "AB1015",
    brand: "Fetch Masters",
    rating: 5.0,
    salesVolume: 214,
  },
  {
    id: 88,
    name: "Dog Treats - Training 1",
    price: 20.0,
    image: "/products/empty.png",
    description: "Dog treats item for training needs.",
    animal: "dog",
    category: "treats",
    subcategory: "Training",
    SKU: "TD1001",
    brand: "WhiskerPlay",
    rating: 3.5,
    salesVolume: 102,
  },
  {
    id: 89,
    name: "Dog Treats - Training 2",
    price: 21.25,
    image: "/products/empty.png",
    description: "Dog treats item for training needs.",
    animal: "dog",
    category: "treats",
    subcategory: "Training",
    SKU: "TD1002",
    brand: "HealthyPaws",
    rating: 4.0,
    salesVolume: 125,
  },
  {
    id: 90,
    name: "Dog Treats - Training 3",
    price: 22.5,
    image: "/products/empty.png",
    description: "Dog treats item for training needs.",
    animal: "dog",
    category: "treats",
    subcategory: "Training",
    SKU: "TD1003",
    brand: "Claw Haven",
    rating: 2.0,
    salesVolume: 40,
  },
  {
    id: 91,
    name: "Dog Treats - Dental 1",
    price: 23.75,
    image: "/products/empty.png",
    description: "Dog treats item for dental needs.",
    animal: "dog",
    category: "treats",
    subcategory: "Dental",
    SKU: "TD1004",
    brand: "FeatherFun",
    rating: 4.5,
    salesVolume: 172,
  },
  {
    id: 92,
    name: "Dog Treats - Dental 2",
    price: 25.0,
    image: "/products/empty.png",
    description: "Dog treats item for dental needs.",
    animal: "dog",
    category: "treats",
    subcategory: "Dental",
    SKU: "TD1005",
    brand: "Tug Time",
    rating: 3.0,
    salesVolume: 86,
  },
  {
    id: 93,
    name: "Dog Treats - Dental 3",
    price: 26.25,
    image: "/products/empty.png",
    description: "Dog treats item for dental needs.",
    animal: "dog",
    category: "treats",
    subcategory: "Dental",
    SKU: "TD1006",
    brand: "PlayPaws",
    rating: 4.0,
    salesVolume: 130,
  },
  {
    id: 94,
    name: "Dog Treats - Natural 1",
    price: 27.5,
    image: "/products/empty.png",
    description: "Dog treats item for natural needs.",
    animal: "dog",
    category: "treats",
    subcategory: "Natural",
    SKU: "TD1007",
    brand: "Natural Branch",
    rating: 2.5,
    salesVolume: 60,
  },
  {
    id: 95,
    name: "Dog Treats - Natural 2",
    price: 28.75,
    image: "/products/empty.png",
    description: "Dog treats item for natural needs.",
    animal: "dog",
    category: "treats",
    subcategory: "Natural",
    SKU: "TD1008",
    brand: "Fetch Masters",
    rating: 5.0,
    salesVolume: 206,
  },
  {
    id: 96,
    name: "Dog Treats - Natural 3",
    price: 30.0,
    image: "/products/empty.png",
    description: "Dog treats item for natural needs.",
    animal: "dog",
    category: "treats",
    subcategory: "Natural",
    SKU: "TD1009",
    brand: "WhiskerPlay",
    rating: 3.5,
    salesVolume: 105,
  },
  {
    id: 97,
    name: "Dog Treats - Chews 1",
    price: 31.25,
    image: "/products/empty.png",
    description: "Dog treats item for chews needs.",
    animal: "dog",
    category: "treats",
    subcategory: "Chews",
    SKU: "TD1010",
    brand: "HealthyPaws",
    rating: 4.0,
    salesVolume: 140,
  },
  {
    id: 98,
    name: "Dog Treats - Chews 2",
    price: 32.5,
    image: "/products/empty.png",
    description: "Dog treats item for chews needs.",
    animal: "dog",
    category: "treats",
    subcategory: "Chews",
    SKU: "TD1011",
    brand: "Claw Haven",
    rating: 2.0,
    salesVolume: 37,
  },
  {
    id: 99,
    name: "Dog Treats - Chews 3",
    price: 33.75,
    image: "/products/empty.png",
    description: "Dog treats item for chews needs.",
    animal: "dog",
    category: "treats",
    subcategory: "Chews",
    SKU: "TD1012",
    brand: "FeatherFun",
    rating: 4.5,
    salesVolume: 189,
  },
  {
    id: 100,
    name: "Dog Treats - Biscuits 1",
    price: 10.0,
    image: "/products/empty.png",
    description: "Dog treats item for biscuits needs.",
    animal: "dog",
    category: "treats",
    subcategory: "Biscuits",
    SKU: "TD1013",
    brand: "Tug Time",
    rating: 3.0,
    salesVolume: 75,
  },
  {
    id: 101,
    name: "Dog Treats - Biscuits 2",
    price: 11.25,
    image: "/products/empty.png",
    description: "Dog treats item for biscuits needs.",
    animal: "dog",
    category: "treats",
    subcategory: "Biscuits",
    SKU: "TD1014",
    brand: "PlayPaws",
    rating: 4.0,
    salesVolume: 122,
  },
  {
    id: 102,
    name: "Dog Treats - Biscuits 3",
    price: 12.5,
    image: "/products/empty.png",
    description: "Dog treats item for biscuits needs.",
    animal: "dog",
    category: "treats",
    subcategory: "Biscuits",
    SKU: "TD1015",
    brand: "Natural Branch",
    rating: 2.5,
    salesVolume: 53,
  },
  {
    id: 103,
    name: "Cat Treats - Crunchy 1",
    price: 13.75,
    image: "/products/empty.png",
    description: "Cat treats item for crunchy needs.",
    animal: "cat",
    category: "treats",
    subcategory: "Crunchy",
    SKU: "TC1001",
    brand: "Fetch Masters",
    rating: 5.0,
    salesVolume: 210,
  },
  {
    id: 104,
    name: "Cat Treats - Crunchy 2",
    price: 15.0,
    image: "/products/empty.png",
    description: "Cat treats item for crunchy needs.",
    animal: "cat",
    category: "treats",
    subcategory: "Crunchy",
    SKU: "TC1002",
    brand: "WhiskerPlay",
    rating: 3.5,
    salesVolume: 99,
  },
  {
    id: 105,
    name: "Cat Treats - Crunchy 3",
    price: 16.25,
    image: "/products/empty.png",
    description: "Cat treats item for crunchy needs.",
    animal: "cat",
    category: "treats",
    subcategory: "Crunchy",
    SKU: "TC1003",
    brand: "HealthyPaws",
    rating: 4.0,
    salesVolume: 144,
  },
  {
    id: 106,
    name: "Cat Treats - Soft 1",
    price: 17.5,
    image: "/products/empty.png",
    description: "Cat treats item for soft needs.",
    animal: "cat",
    category: "treats",
    subcategory: "Soft",
    SKU: "TC1004",
    brand: "Claw Haven",
    rating: 2.0,
    salesVolume: 45,
  },
  {
    id: 107,
    name: "Cat Treats - Soft 2",
    price: 18.75,
    image: "/products/empty.png",
    description: "Cat treats item for soft needs.",
    animal: "cat",
    category: "treats",
    subcategory: "Soft",
    SKU: "TC1005",
    brand: "FeatherFun",
    rating: 4.5,
    salesVolume: 175,
  },
  {
    id: 108,
    name: "Cat Treats - Soft 3",
    price: 20.0,
    image: "/products/empty.png",
    description: "Cat treats item for soft needs.",
    animal: "cat",
    category: "treats",
    subcategory: "Soft",
    SKU: "TC1006",
    brand: "Tug Time",
    rating: 3.0,
    salesVolume: 88,
  },
  {
    id: 109,
    name: "Cat Treats - Dental 1",
    price: 21.25,
    image: "/products/empty.png",
    description: "Cat treats item for dental needs.",
    animal: "cat",
    category: "treats",
    subcategory: "Dental",
    SKU: "TC1007",
    brand: "PlayPaws",
    rating: 4.0,
    salesVolume: 147,
  },
  {
    id: 110,
    name: "Cat Treats - Dental 2",
    price: 22.5,
    image: "/products/empty.png",
    description: "Cat treats item for dental needs.",
    animal: "cat",
    category: "treats",
    subcategory: "Dental",
    SKU: "TC1008",
    brand: "Natural Branch",
    rating: 2.5,
    salesVolume: 64,
  },
  {
    id: 111,
    name: "Cat Treats - Dental 3",
    price: 23.75,
    image: "/products/empty.png",
    description: "Cat treats item for dental needs.",
    animal: "cat",
    category: "treats",
    subcategory: "Dental",
    SKU: "TC1009",
    brand: "Fetch Masters",
    rating: 5.0,
    salesVolume: 209,
  },
  {
    id: 112,
    name: "Cat Treats - Catnip 1",
    price: 25.0,
    image: "/products/empty.png",
    description: "Cat treats item for catnip needs.",
    animal: "cat",
    category: "treats",
    subcategory: "Catnip",
    SKU: "TC1010",
    brand: "WhiskerPlay",
    rating: 3.5,
    salesVolume: 103,
  },
  {
    id: 113,
    name: "Cat Treats - Catnip 2",
    price: 26.25,
    image: "/products/empty.png",
    description: "Cat treats item for catnip needs.",
    animal: "cat",
    category: "treats",
    subcategory: "Catnip",
    SKU: "TC1011",
    brand: "HealthyPaws",
    rating: 4.0,
    salesVolume: 148,
  },
  {
    id: 114,
    name: "Cat Treats - Catnip 3",
    price: 27.5,
    image: "/products/empty.png",
    description: "Cat treats item for catnip needs.",
    animal: "cat",
    category: "treats",
    subcategory: "Catnip",
    SKU: "TC1012",
    brand: "Claw Haven",
    rating: 2.0,
    salesVolume: 46,
  },
  {
    id: 115,
    name: "Cat Treats - Freeze-Dried 1",
    price: 28.75,
    image: "/products/empty.png",
    description: "Cat treats item for freeze-dried needs.",
    animal: "cat",
    category: "treats",
    subcategory: "Freeze-Dried",
    SKU: "TC1013",
    brand: "FeatherFun",
    rating: 4.5,
    salesVolume: 182,
  },
  {
    id: 116,
    name: "Cat Treats - Freeze-Dried 2",
    price: 30.0,
    image: "/products/empty.png",
    description: "Cat treats item for freeze-dried needs.",
    animal: "cat",
    category: "treats",
    subcategory: "Freeze-Dried",
    SKU: "TC1014",
    brand: "Tug Time",
    rating: 3.0,
    salesVolume: 90,
  },
  {
    id: 117,
    name: "Cat Treats - Freeze-Dried 3",
    price: 31.25,
    image: "/products/empty.png",
    description: "Cat treats item for freeze-dried needs.",
    animal: "cat",
    category: "treats",
    subcategory: "Freeze-Dried",
    SKU: "TC1015",
    brand: "PlayPaws",
    rating: 4.0,
    salesVolume: 146,
  },
  {
    id: 118,
    name: "Bird Treats - Sticks 1",
    price: 32.5,
    image: "/products/empty.png",
    description: "Bird treats item for sticks needs.",
    animal: "bird",
    category: "treats",
    subcategory: "Sticks",
    SKU: "TB1001",
    brand: "Natural Branch",
    rating: 2.5,
    salesVolume: 65,
  },
  {
    id: 119,
    name: "Bird Treats - Sticks 2",
    price: 33.75,
    image: "/products/empty.png",
    description: "Bird treats item for sticks needs.",
    animal: "bird",
    category: "treats",
    subcategory: "Sticks",
    SKU: "TB1002",
    brand: "Fetch Masters",
    rating: 5.0,
    salesVolume: 211,
  },
  {
    id: 120,
    name: "Bird Treats - Sticks 3",
    price: 10.0,
    image: "/products/empty.png",
    description: "Bird treats item for sticks needs.",
    animal: "bird",
    category: "treats",
    subcategory: "Sticks",
    SKU: "TB1003",
    brand: "WhiskerPlay",
    rating: 3.5,
    salesVolume: 100,
  },
  {
    id: 121,
    name: "Bird Treats - Fruit 1",
    price: 11.25,
    image: "/products/empty.png",
    description: "Bird treats item for fruit needs.",
    animal: "bird",
    category: "treats",
    subcategory: "Fruit",
    SKU: "TB1004",
    brand: "HealthyPaws",
    rating: 4.0,
    salesVolume: 151,
  },
  {
    id: 122,
    name: "Bird Treats - Fruit 2",
    price: 12.5,
    image: "/products/empty.png",
    description: "Bird treats item for fruit needs.",
    animal: "bird",
    category: "treats",
    subcategory: "Fruit",
    SKU: "TB1005",
    brand: "Claw Haven",
    rating: 2.0,
    salesVolume: 48,
  },
  {
    id: 123,
    name: "Bird Treats - Fruit 3",
    price: 13.75,
    image: "/products/empty.png",
    description: "Bird treats item for fruit needs.",
    animal: "bird",
    category: "treats",
    subcategory: "Fruit",
    SKU: "TB1006",
    brand: "FeatherFun",
    rating: 4.5,
    salesVolume: 186,
  },
  {
    id: 124,
    name: "Bird Treats - Seed Balls 1",
    price: 15.0,
    image: "/products/empty.png",
    description: "Bird treats item for seed balls needs.",
    animal: "bird",
    category: "treats",
    subcategory: "Seed Balls",
    SKU: "TB1007",
    brand: "Tug Time",
    rating: 3.0,
    salesVolume: 92,
  },
  {
    id: 125,
    name: "Bird Treats - Seed Balls 2",
    price: 16.25,
    image: "/products/empty.png",
    description: "Bird treats item for seed balls needs.",
    animal: "bird",
    category: "treats",
    subcategory: "Seed Balls",
    SKU: "TB1008",
    brand: "PlayPaws",
    rating: 4.0,
    salesVolume: 152,
  },
  {
    id: 126,
    name: "Bird Treats - Seed Balls 3",
    price: 17.5,
    image: "/products/empty.png",
    description: "Bird treats item for seed balls needs.",
    animal: "bird",
    category: "treats",
    subcategory: "Seed Balls",
    SKU: "TB1009",
    brand: "Natural Branch",
    rating: 2.5,
    salesVolume: 66,
  },
  {
    id: 127,
    name: "Bird Treats - Millet Sprays 1",
    price: 18.75,
    image: "/products/empty.png",
    description: "Bird treats item for millet sprays needs.",
    animal: "bird",
    category: "treats",
    subcategory: "Millet Sprays",
    SKU: "TB1010",
    brand: "Fetch Masters",
    rating: 5.0,
    salesVolume: 218,
  },
  {
    id: 128,
    name: "Bird Treats - Millet Sprays 2",
    price: 20.0,
    image: "/products/empty.png",
    description: "Bird treats item for millet sprays needs.",
    animal: "bird",
    category: "treats",
    subcategory: "Millet Sprays",
    SKU: "TB1011",
    brand: "WhiskerPlay",
    rating: 3.5,
    salesVolume: 110,
  },
  {
    id: 129,
    name: "Bird Treats - Millet Sprays 3",
    price: 21.25,
    image: "/products/empty.png",
    description: "Bird treats item for millet sprays needs.",
    animal: "bird",
    category: "treats",
    subcategory: "Millet Sprays",
    SKU: "TB1012",
    brand: "HealthyPaws",
    rating: 4.0,
    salesVolume: 153,
  },
  {
    id: 130,
    name: "Bird Treats - Nutritional 1",
    price: 22.5,
    image: "/products/empty.png",
    description: "Bird treats item for nutritional needs.",
    animal: "bird",
    category: "treats",
    subcategory: "Nutritional",
    SKU: "TB1013",
    brand: "Claw Haven",
    rating: 2.0,
    salesVolume: 49,
  },
  {
    id: 131,
    name: "Bird Treats - Nutritional 2",
    price: 23.75,
    image: "/products/empty.png",
    description: "Bird treats item for nutritional needs.",
    animal: "bird",
    category: "treats",
    subcategory: "Nutritional",
    SKU: "TB1014",
    brand: "FeatherFun",
    rating: 4.5,
    salesVolume: 190,
  },
  {
    id: 132,
    name: "Bird Treats - Nutritional 3",
    price: 25.0,
    image: "/products/empty.png",
    description: "Bird treats item for nutritional needs.",
    animal: "bird",
    category: "treats",
    subcategory: "Nutritional",
    SKU: "TB1015",
    brand: "Tug Time",
    rating: 3.0,
    salesVolume: 94,
  },
  {
    id: 133,
    name: "Dog Toys - Chew 1",
    price: 26.25,
    image: "/products/empty.png",
    description: "Dog toys item for chew needs.",
    animal: "dog",
    category: "toys",
    subcategory: "Chew",
    SKU: "ToyD1001",
    brand: "PlayPaws",
    rating: 4.0,
    salesVolume: 154,
  },
  {
    id: 134,
    name: "Dog Toys - Chew 2",
    price: 27.5,
    image: "/products/empty.png",
    description: "Dog toys item for chew needs.",
    animal: "dog",
    category: "toys",
    subcategory: "Chew",
    SKU: "ToyD1002",
    brand: "Natural Branch",
    rating: 2.5,
    salesVolume: 68,
  },
  {
    id: 135,
    name: "Dog Toys - Chew 3",
    price: 28.75,
    image: "/products/empty.png",
    description: "Dog toys item for chew needs.",
    animal: "dog",
    category: "toys",
    subcategory: "Chew",
    SKU: "ToyD1003",
    brand: "Fetch Masters",
    rating: 5.0,
    salesVolume: 219,
  },
  {
    id: 136,
    name: "Dog Toys - Plush 1",
    price: 30.0,
    image: "/products/empty.png",
    description: "Dog toys item for plush needs.",
    animal: "dog",
    category: "toys",
    subcategory: "Plush",
    SKU: "ToyD1004",
    brand: "WhiskerPlay",
    rating: 3.5,
    salesVolume: 111,
  },
  {
    id: 137,
    name: "Dog Toys - Plush 2",
    price: 31.25,
    image: "/products/empty.png",
    description: "Dog toys item for plush needs.",
    animal: "dog",
    category: "toys",
    subcategory: "Plush",
    SKU: "ToyD1005",
    brand: "HealthyPaws",
    rating: 4.0,
    salesVolume: 155,
  },
  {
    id: 138,
    name: "Dog Toys - Plush 3",
    price: 32.5,
    image: "/products/empty.png",
    description: "Dog toys item for plush needs.",
    animal: "dog",
    category: "toys",
    subcategory: "Plush",
    SKU: "ToyD1006",
    brand: "Claw Haven",
    rating: 2.0,
    salesVolume: 50,
  },
  {
    id: 139,
    name: "Dog Toys - Interactive 1",
    price: 33.75,
    image: "/products/empty.png",
    description: "Dog toys item for interactive needs.",
    animal: "dog",
    category: "toys",
    subcategory: "Interactive",
    SKU: "ToyD1007",
    brand: "FeatherFun",
    rating: 4.5,
    salesVolume: 191,
  },
  {
    id: 140,
    name: "Dog Toys - Interactive 2",
    price: 10.0,
    image: "/products/empty.png",
    description: "Dog toys item for interactive needs.",
    animal: "dog",
    category: "toys",
    subcategory: "Interactive",
    SKU: "ToyD1008",
    brand: "Tug Time",
    rating: 3.0,
    salesVolume: 95,
  },
  {
    id: 141,
    name: "Dog Toys - Interactive 3",
    price: 11.25,
    image: "/products/empty.png",
    description: "Dog toys item for interactive needs.",
    animal: "dog",
    category: "toys",
    subcategory: "Interactive",
    SKU: "ToyD1009",
    brand: "PlayPaws",
    rating: 4.0,
    salesVolume: 157,
  },
  {
    id: 142,
    name: "Dog Toys - Fetch 1",
    price: 12.5,
    image: "/products/empty.png",
    description: "Dog toys item for fetch needs.",
    animal: "dog",
    category: "toys",
    subcategory: "Fetch",
    SKU: "ToyD1010",
    brand: "Natural Branch",
    rating: 2.5,
    salesVolume: 69,
  },
  {
    id: 143,
    name: "Dog Toys - Fetch 2",
    price: 13.75,
    image: "/products/empty.png",
    description: "Dog toys item for fetch needs.",
    animal: "dog",
    category: "toys",
    subcategory: "Fetch",
    SKU: "ToyD1011",
    brand: "Fetch Masters",
    rating: 5.0,
    salesVolume: 220,
  },
  {
    id: 144,
    name: "Dog Toys - Fetch 3",
    price: 15.0,
    image: "/products/empty.png",
    description: "Dog toys item for fetch needs.",
    animal: "dog",
    category: "toys",
    subcategory: "Fetch",
    SKU: "ToyD1012",
    brand: "WhiskerPlay",
    rating: 3.5,
    salesVolume: 113,
  },
  {
    id: 145,
    name: "Dog Toys - Rope 1",
    price: 16.25,
    image: "/products/empty.png",
    description: "Dog toys item for rope needs.",
    animal: "dog",
    category: "toys",
    subcategory: "Rope",
    SKU: "ToyD1013",
    brand: "HealthyPaws",
    rating: 4.0,
    salesVolume: 158,
  },
  {
    id: 146,
    name: "Dog Toys - Rope 2",
    price: 17.5,
    image: "/products/empty.png",
    description: "Dog toys item for rope needs.",
    animal: "dog",
    category: "toys",
    subcategory: "Rope",
    SKU: "ToyD1014",
    brand: "Claw Haven",
    rating: 2.0,
    salesVolume: 51,
  },
  {
    id: 147,
    name: "Dog Toys - Rope 3",
    price: 18.75,
    image: "/products/empty.png",
    description: "Dog toys item for rope needs.",
    animal: "dog",
    category: "toys",
    subcategory: "Rope",
    SKU: "ToyD1015",
    brand: "FeatherFun",
    rating: 4.5,
    salesVolume: 193,
  },
  {
    id: 148,
    name: "Cat Toys - Interactive 1",
    price: 20.0,
    image: "/products/empty.png",
    description: "Cat toys item for interactive needs.",
    animal: "cat",
    category: "toys",
    subcategory: "Interactive",
    SKU: "ToyC1001",
    brand: "Tug Time",
    rating: 3.0,
    salesVolume: 96,
  },
  {
    id: 149,
    name: "Cat Toys - Interactive 2",
    price: 21.25,
    image: "/products/empty.png",
    description: "Cat toys item for interactive needs.",
    animal: "cat",
    category: "toys",
    subcategory: "Interactive",
    SKU: "ToyC1002",
    brand: "PlayPaws",
    rating: 4.0,
    salesVolume: 159,
  },
  {
    id: 150,
    name: "Cat Toys - Interactive 3",
    price: 22.5,
    image: "/products/empty.png",
    description: "Cat toys item for interactive needs.",
    animal: "cat",
    category: "toys",
    subcategory: "Interactive",
    SKU: "ToyC1003",
    brand: "Natural Branch",
    rating: 2.5,
    salesVolume: 70,
  },
  {
    id: 151,
    name: "Cat Toys - Feather 1",
    price: 23.75,
    image: "/products/empty.png",
    description: "Cat toys item for feather needs.",
    animal: "cat",
    category: "toys",
    subcategory: "Feather",
    SKU: "ToyC1004",
    brand: "Fetch Masters",
    rating: 5.0,
    salesVolume: 222,
  },
  {
    id: 152,
    name: "Cat Toys - Feather 2",
    price: 25.0,
    image: "/products/empty.png",
    description: "Cat toys item for feather needs.",
    animal: "cat",
    category: "toys",
    subcategory: "Feather",
    SKU: "ToyC1005",
    brand: "WhiskerPlay",
    rating: 3.5,
    salesVolume: 114,
  },
  {
    id: 153,
    name: "Cat Toys - Feather 3",
    price: 26.25,
    image: "/products/empty.png",
    description: "Cat toys item for feather needs.",
    animal: "cat",
    category: "toys",
    subcategory: "Feather",
    SKU: "ToyC1006",
    brand: "HealthyPaws",
    rating: 4.0,
    salesVolume: 160,
  },
  {
    id: 154,
    name: "Cat Toys - Balls 1",
    price: 27.5,
    image: "/products/empty.png",
    description: "Cat toys item for balls needs.",
    animal: "cat",
    category: "toys",
    subcategory: "Balls",
    SKU: "ToyC1007",
    brand: "Claw Haven",
    rating: 2.0,
    salesVolume: 32,
  },
  {
    id: 155,
    name: "Cat Toys - Balls 2",
    price: 28.75,
    image: "/products/empty.png",
    description: "Cat toys item for balls needs.",
    animal: "cat",
    category: "toys",
    subcategory: "Balls",
    SKU: "ToyC1008",
    brand: "FeatherFun",
    rating: 4.5,
    salesVolume: 194,
  },
  {
    id: 156,
    name: "Cat Toys - Balls 3",
    price: 30.0,
    image: "/products/empty.png",
    description: "Cat toys item for balls needs.",
    animal: "cat",
    category: "toys",
    subcategory: "Balls",
    SKU: "ToyC1009",
    brand: "Tug Time",
    rating: 3.0,
    salesVolume: 91,
  },
  {
    id: 157,
    name: "Cat Toys - Catnip 1",
    price: 31.25,
    image: "/products/empty.png",
    description: "Cat toys item for catnip needs.",
    animal: "cat",
    category: "toys",
    subcategory: "Catnip",
    SKU: "ToyC1010",
    brand: "PlayPaws",
    rating: 4.0,
    salesVolume: 161,
  },
  {
    id: 158,
    name: "Cat Toys - Catnip 2",
    price: 32.5,
    image: "/products/empty.png",
    description: "Cat toys item for catnip needs.",
    animal: "cat",
    category: "toys",
    subcategory: "Catnip",
    SKU: "ToyC1011",
    brand: "Natural Branch",
    rating: 2.5,
    salesVolume: 72,
  },
  {
    id: 159,
    name: "Cat Toys - Catnip 3",
    price: 33.75,
    image: "/products/empty.png",
    description: "Cat toys item for catnip needs.",
    animal: "cat",
    category: "toys",
    subcategory: "Catnip",
    SKU: "ToyC1012",
    brand: "Fetch Masters",
    rating: 5.0,
    salesVolume: 223,
  },
  {
    id: 160,
    name: "Cat Toys - Tunnels 1",
    price: 10.0,
    image: "/products/empty.png",
    description: "Cat toys item for tunnels needs.",
    animal: "cat",
    category: "toys",
    subcategory: "Tunnels",
    SKU: "ToyC1013",
    brand: "WhiskerPlay",
    rating: 3.5,
    salesVolume: 115,
  },
  {
    id: 161,
    name: "Cat Toys - Tunnels 2",
    price: 11.25,
    image: "/products/empty.png",
    description: "Cat toys item for tunnels needs.",
    animal: "cat",
    category: "toys",
    subcategory: "Tunnels",
    SKU: "ToyC1014",
    brand: "HealthyPaws",
    rating: 4.0,
    salesVolume: 162,
  },
  {
    id: 162,
    name: "Cat Toys - Tunnels 3",
    price: 12.5,
    image: "/products/empty.png",
    description: "Cat toys item for tunnels needs.",
    animal: "cat",
    category: "toys",
    subcategory: "Tunnels",
    SKU: "ToyC1015",
    brand: "Claw Haven",
    rating: 2.0,
    salesVolume: 33,
  },
  {
    id: 163,
    name: "Bird Toys - Mirrors 1",
    price: 13.75,
    image: "/products/empty.png",
    description: "Bird toys item for mirrors needs.",
    animal: "bird",
    category: "toys",
    subcategory: "Mirrors",
    SKU: "ToyB1001",
    brand: "FeatherFun",
    rating: 4.5,
    salesVolume: 195,
  },
  {
    id: 164,
    name: "Bird Toys - Mirrors 2",
    price: 15.0,
    image: "/products/empty.png",
    description: "Bird toys item for mirrors needs.",
    animal: "bird",
    category: "toys",
    subcategory: "Mirrors",
    SKU: "ToyB1002",
    brand: "Tug Time",
    rating: 3.0,
    salesVolume: 83,
  },
  {
    id: 165,
    name: "Bird Toys - Mirrors 3",
    price: 16.25,
    image: "/products/empty.png",
    description: "Bird toys item for mirrors needs.",
    animal: "bird",
    category: "toys",
    subcategory: "Mirrors",
    SKU: "ToyB1003",
    brand: "PlayPaws",
    rating: 4.0,
    salesVolume: 163,
  },
  {
    id: 166,
    name: "Bird Toys - Bells 1",
    price: 17.5,
    image: "/products/empty.png",
    description: "Bird toys item for bells needs.",
    animal: "bird",
    category: "toys",
    subcategory: "Bells",
    SKU: "ToyB1004",
    brand: "Natural Branch",
    rating: 2.5,
    salesVolume: 74,
  },
  {
    id: 167,
    name: "Bird Toys - Bells 2",
    price: 18.75,
    image: "/products/empty.png",
    description: "Bird toys item for bells needs.",
    animal: "bird",
    category: "toys",
    subcategory: "Bells",
    SKU: "ToyB1005",
    brand: "Fetch Masters",
    rating: 5.0,
    salesVolume: 224,
  },
  {
    id: 168,
    name: "Bird Toys - Bells 3",
    price: 20.0,
    image: "/products/empty.png",
    description: "Bird toys item for bells needs.",
    animal: "bird",
    category: "toys",
    subcategory: "Bells",
    SKU: "ToyB1006",
    brand: "WhiskerPlay",
    rating: 3.5,
    salesVolume: 116,
  },
  {
    id: 169,
    name: "Bird Toys - Swings 1",
    price: 21.25,
    image: "/products/empty.png",
    description: "Bird toys item for swings needs.",
    animal: "bird",
    category: "toys",
    subcategory: "Swings",
    SKU: "ToyB1007",
    brand: "HealthyPaws",
    rating: 4.0,
    salesVolume: 164,
  },
  {
    id: 170,
    name: "Bird Toys - Swings 2",
    price: 22.5,
    image: "/products/empty.png",
    description: "Bird toys item for swings needs.",
    animal: "bird",
    category: "toys",
    subcategory: "Swings",
    SKU: "ToyB1008",
    brand: "Claw Haven",
    rating: 2.0,
    salesVolume: 34,
  },
  {
    id: 171,
    name: "Bird Toys - Swings 3",
    price: 23.75,
    image: "/products/empty.png",
    description: "Bird toys item for swings needs.",
    animal: "bird",
    category: "toys",
    subcategory: "Swings",
    SKU: "ToyB1009",
    brand: "FeatherFun",
    rating: 4.5,
    salesVolume: 197,
  },
  {
    id: 172,
    name: "Bird Toys - Foraging 1",
    price: 25.0,
    image: "/products/empty.png",
    description: "Bird toys item for foraging needs.",
    animal: "bird",
    category: "toys",
    subcategory: "Foraging",
    SKU: "ToyB1010",
    brand: "Tug Time",
    rating: 3.0,
    salesVolume: 80,
  },
  {
    id: 173,
    name: "Bird Toys - Foraging 2",
    price: 26.25,
    image: "/products/empty.png",
    description: "Bird toys item for foraging needs.",
    animal: "bird",
    category: "toys",
    subcategory: "Foraging",
    SKU: "ToyB1011",
    brand: "PlayPaws",
    rating: 4.0,
    salesVolume: 165,
  },
  {
    id: 174,
    name: "Bird Toys - Foraging 3",
    price: 27.5,
    image: "/products/empty.png",
    description: "Bird toys item for foraging needs.",
    animal: "bird",
    category: "toys",
    subcategory: "Foraging",
    SKU: "ToyB1012",
    brand: "Natural Branch",
    rating: 2.5,
    salesVolume: 29,
  },
  {
    id: 175,
    name: "Bird Toys - Wooden 1",
    price: 28.75,
    image: "/products/empty.png",
    description: "Bird toys item for wooden needs.",
    animal: "bird",
    category: "toys",
    subcategory: "Wooden",
    SKU: "ToyB1013",
    brand: "Fetch Masters",
    rating: 5.0,
    salesVolume: 225,
  },
  {
    id: 176,
    name: "Bird Toys - Wooden 2",
    price: 30.0,
    image: "/products/empty.png",
    description: "Bird toys item for wooden needs.",
    animal: "bird",
    category: "toys",
    subcategory: "Wooden",
    SKU: "ToyB1014",
    brand: "WhiskerPlay",
    rating: 3.5,
    salesVolume: 117,
  },
  {
    id: 177,
    name: "Bird Toys - Wooden 3",
    price: 31.25,
    image: "/products/empty.png",
    description: "Bird toys item for wooden needs.",
    animal: "bird",
    category: "toys",
    subcategory: "Wooden",
    SKU: "ToyB1015",
    brand: "HealthyPaws",
    rating: 4.0,
    salesVolume: 166,
  },
];

export default productData;
