// lib/products.js
export const products = [
  // Food category
  {
    id: 1,
    name: "Premium Dog Food",
    price: 29.99,
    image: "/dog-food.jpg",
    description: "Nutritious food for your canine companion.",
    animalType: "dog",
    category: "food",
    subcategory: "dry",
  },
  {
    id: 2,
    name: "Grain-Free Cat Food",
    price: 24.99,
    image: "/cat-food.jpg",
    description: "Healthy grain-free option for your feline friend.",
    animalType: "cat",
    category: "food",
    subcategory: "dry",
  },
  {
    id: 3,
    name: "Bird Seed Mix",
    price: 12.99,
    image: "/bird-food.jpg",
    description: "Nutritious seed mix for your feathered friends.",
    animalType: "bird",
    category: "food",
    subcategory: "seeds",
  },
  {
    id: 4,
    name: "Wet Dog Food",
    price: 15.99,
    image: "/wet-dog-food.jpg",
    description: "Delicious wet food for dogs.",
    animalType: "dog",
    category: "food",
    subcategory: "wet",
  },

  // Accessories category
  {
    id: 5,
    name: "Dog Collar",
    price: 14.99,
    image: "/dog-collar.jpg",
    description: "Comfortable and durable dog collar.",
    animalType: "dog",
    category: "accessories",
    subcategory: "collars",
  },
  {
    id: 6,
    name: "Cat Bed",
    price: 34.99,
    image: "/cat-bed.jpg",
    description: "Cozy bed for your cat to nap in.",
    animalType: "cat",
    category: "accessories",
    subcategory: "beds",
  },
  {
    id: 7,
    name: "Bird Cage",
    price: 59.99,
    image: "/bird-cage.jpg",
    description: "Spacious cage for your feathered friends.",
    animalType: "bird",
    category: "accessories",
    subcategory: "cages",
  },
  {
    id: 8,
    name: "Dog Leash",
    price: 12.99,
    image: "/dog-leash.jpg",
    description: "Strong and reliable dog leash.",
    animalType: "dog",
    category: "accessories",
    subcategory: "leashes",
  },

  // Treats category
  {
    id: 9,
    name: "Dental Dog Treats",
    price: 8.99,
    image: "/dog-treats.jpg",
    description: "Helps clean teeth while rewarding your dog.",
    animalType: "dog",
    category: "treats",
    subcategory: "dental",
  },
  {
    id: 10,
    name: "Catnip Treats",
    price: 6.99,
    image: "/cat-treats.jpg",
    description: "Irresistible treats with catnip.",
    animalType: "cat",
    category: "treats",
    subcategory: "catnip",
  },
  {
    id: 11,
    name: "Bird Treat Sticks",
    price: 4.99,
    image: "/bird-treats.jpg",
    description: "Nutritious treat sticks for birds.",
    animalType: "bird",
    category: "treats",
    subcategory: "sticks",
  },
  {
    id: 12,
    name: "Training Dog Treats",
    price: 7.99,
    image: "/training-treats.jpg",
    description: "Small treats perfect for training sessions.",
    animalType: "dog",
    category: "treats",
    subcategory: "training",
  },

  // Toys category
  {
    id: 13,
    name: "Cat Toy",
    price: 9.99,
    image: "/cat-toy.jpg",
    description: "Fun and safe toy for your cat.",
    animalType: "cat",
    category: "toys",
    subcategory: "interactive",
  },
  {
    id: 14,
    name: "Chew Toy",
    price: 11.99,
    image: "/chew-toy.jpg",
    description: "Durable chew toy for dogs.",
    animalType: "dog",
    category: "toys",
    subcategory: "chew",
  },
  {
    id: 15,
    name: "Bird Mirror Toy",
    price: 8.99,
    image: "/bird-toy.jpg",
    description: "Entertaining mirror toy for birds.",
    animalType: "bird",
    category: "toys",
    subcategory: "mirror",
  },
  {
    id: 16,
    name: "Plush Squeaky Toy",
    price: 10.99,
    image: "/plush-toy.jpg",
    description: "Soft plush toy with squeaker for dogs.",
    animalType: "dog",
    category: "toys",
    subcategory: "plush",
  },
];
