// lib/products.js
export const products = [
  // Food category
  {
    id: 1,
    name: "Premium Dog Food",
    price: 29.99,
    image: "/dog-food.jpg",
    description: "Nutritious food for your canine companion.",
    animalType: "dog",
    category: "food",
    subcategory: "dry",
    SKU: "PF1001",
    brand: "Paw Natural",
  },
  {
    id: 2,
    name: "Grain-Free Cat Food",
    price: 24.99,
    image: "/cat-food.jpg",
    description: "Healthy grain-free option for your feline friend.",
    animalType: "cat",
    category: "food",
    subcategory: "dry",
    SKU: "PF1002",
    brand: "Whisker Well",
  },
  {
    id: 3,
    name: "Bird Seed Mix",
    price: 12.99,
    image: "https://images.unsplash.com/photo-1596436889106-be35e8433c6f?w=300",
    description: "Nutritious seed mix for your feathered friends.",
    animalType: "bird",
    category: "food",
    subcategory: "seeds",
    SKU: "PF1003",
    brand: "Feather Feast",
  },
  {
    id: 4,
    name: "Wet Dog Food",
    price: 15.99,
    image: "https://images.unsplash.com/photo-1589923188937-cb64779f4abe?w=300",
    description: "Delicious wet food for dogs.",
    animalType: "dog",
    category: "food",
    subcategory: "wet",
    SKU: "PF1004",
    brand: "Canine Cuisine",
  },
  {
    id: 5,
    name: "Salmon Dry Cat Food",
    price: 26.99,
    image: "https://images.unsplash.com/photo-1543852786-1cf6624b9987?w=300",
    description: "Protein-rich salmon formula for cats.",
    animalType: "cat",
    category: "food",
    subcategory: "dry",
    SKU: "PF1005",
    brand: "Finicky Feast",
  },
  {
    id: 6,
    name: "Large Breed Dog Food",
    price: 34.99,
    image: "https://images.unsplash.com/photo-1560807707-8cc77767d783?w=300",
    description: "Specially formulated for large breed dogs.",
    animalType: "dog",
    category: "food",
    subcategory: "dry",
    SKU: "PF1006",
    brand: "Big Barker",
  },
  {
    id: 7,
    name: "Organic Bird Pellets",
    price: 14.99,
    image: "https://images.unsplash.com/photo-1516545595035-b494dd0161e4?w=300",
    description: "Organic nutrition for healthy birds.",
    animalType: "bird",
    category: "food",
    subcategory: "pellets",
    SKU: "PF1007",
    brand: "Avian Organics",
  },
  {
    id: 8,
    name: "Puppy Formula Food",
    price: 27.99,
    image: "https://images.unsplash.com/photo-1554692918-08fa0fdc9db3?w=300",
    description: "Complete nutrition for growing puppies.",
    animalType: "dog",
    category: "food",
    subcategory: "dry",
    SKU: "PF1008",
    brand: "Happy Pup",
  },
  {
    id: 9,
    name: "Senior Cat Formula",
    price: 22.99,
    image: "https://images.unsplash.com/photo-1592194996308-7b43878e84a6?w=300",
    description: "Special formula for senior cats.",
    animalType: "cat",
    category: "food",
    subcategory: "dry",
    SKU: "PF1009",
    brand: "Golden Years",
  },
  {
    id: 10,
    name: "Parrot Fruit Mix",
    price: 16.99,
    image: "https://images.unsplash.com/photo-1472491235688-bdc81a6d63fa?w=300",
    description: "Tropical fruit mix for parrots.",
    animalType: "bird",
    category: "food",
    subcategory: "mix",
    SKU: "PF1010",
    brand: "Tropical Wings",
  },

  // Accessories category
  {
    id: 11,
    name: "Designer Dog Collar",
    price: 24.99,
    image: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=300",
    description: "Comfortable and durable designer dog collar.",
    animalType: "dog",
    category: "accessories",
    subcategory: "collars",
    SKU: "AC2001",
    brand: "Paw Style",
  },
  {
    id: 12,
    name: "Plush Cat Bed",
    price: 34.99,
    image: "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=300",
    description: "Cozy bed for your cat to nap in.",
    animalType: "cat",
    category: "accessories",
    subcategory: "beds",
    SKU: "AC2002",
    brand: "Cozy Pets",
  },
  {
    id: 13,
    name: "Deluxe Bird Cage",
    price: 89.99,
    image: "https://images.unsplash.com/photo-1578779668325-78eb208bfd78?w=300",
    description: "Spacious cage for your feathered friends.",
    animalType: "bird",
    category: "accessories",
    subcategory: "cages",
    SKU: "AC2003",
    brand: "Avian Living",
  },
  {
    id: 14,
    name: "Retractable Dog Leash",
    price: 22.99,
    image: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=300",
    description: "Strong and reliable retractable dog leash.",
    animalType: "dog",
    category: "accessories",
    subcategory: "leashes",
    SKU: "AC2004",
    brand: "Walk Easy",
  },
  {
    id: 15,
    name: "Scratching Post",
    price: 39.99,
    image: "https://images.unsplash.com/photo-1533738363-b7f9aef128ce?w=300",
    description: "Premium scratching post for cats.",
    animalType: "cat",
    category: "accessories",
    subcategory: "furniture",
    SKU: "AC2005",
    brand: "Feline Fun",
  },
  {
    id: 16,
    name: "Bird Play Gym",
    price: 45.99,
    image: "https://images.unsplash.com/photo-1551085255-e6b9537e0636?w=300",
    description: "Interactive play gym for birds.",
    animalType: "bird",
    category: "accessories",
    subcategory: "toys",
    SKU: "AC2006",
    brand: "Feather Fun",
  },
  {
    id: 17,
    name: "Dog Harness",
    price: 28.99,
    image: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=300",
    description: "Comfortable no-pull dog harness.",
    animalType: "dog",
    category: "accessories",
    subcategory: "harnesses",
    SKU: "AC2007",
    brand: "Safe Walk",
  },
  {
    id: 18,
    name: "Automatic Feeder",
    price: 59.99,
    image: "https://images.unsplash.com/photo-1576239312917-259a6a36cf6d?w=300",
    description: "Automatic pet feeder with timer.",
    animalType: "cat",
    category: "accessories",
    subcategory: "feeders",
    SKU: "AC2008",
    brand: "Pet Tech",
  },
  {
    id: 19,
    name: "Travel Bird Carrier",
    price: 42.99,
    image: "https://images.unsplash.com/photo-1596461404969-9d24c16f3da9?w=300",
    description: "Secure carrier for traveling with birds.",
    animalType: "bird",
    category: "accessories",
    subcategory: "carriers",
    SKU: "AC2009",
    brand: "Travel Safe",
  },
  {
    id: 20,
    name: "Heated Pet Bed",
    price: 49.99,
    image: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=300",
    description: "Warm heated bed for pets.",
    animalType: "dog",
    category: "accessories",
    subcategory: "beds",
    SKU: "AC2010",
    brand: "Cozy Warmth",
  },

  // Treats category
  {
    id: 21,
    name: "Dental Chew Treats",
    price: 12.99,
    image: "https://images.unsplash.com/photo-1554692918-08fa0fdc9db3?w=300",
    description: "Helps clean teeth while rewarding your dog.",
    animalType: "dog",
    category: "treats",
    subcategory: "dental",
    SKU: "TR3001",
    brand: "Healthy Smile",
  },
  {
    id: 22,
    name: "Organic Catnip Treats",
    price: 8.99,
    image: "https://images.unsplash.com/photo-1574235664855-4c5a5d4a8b1c?w=300",
    description: "Irresistible organic treats with catnip.",
    animalType: "cat",
    category: "treats",
    subcategory: "catnip",
    SKU: "TR3002",
    brand: "Natural Nibbles",
  },
  {
    id: 23,
    name: "Fruit Blend Treat Sticks",
    price: 7.99,
    image: "https://images.unsplash.com/photo-1551085255-e6b9537e0636?w=300",
    description: "Nutritious fruit blend treat sticks for birds.",
    animalType: "bird",
    category: "treats",
    subcategory: "sticks",
    SKU: "TR3003",
    brand: "Tropical Bites",
  },
  {
    id: 24,
    name: "Training Reward Treats",
    price: 9.99,
    image: "https://images.unsplash.com/photo-1554692918-08fa0fdc9db3?w=300",
    description: "Small treats perfect for training sessions.",
    animalType: "dog",
    category: "treats",
    subcategory: "training",
    SKU: "TR3004",
    brand: "Smart Train",
  },
  {
    id: 25,
    name: "Salmon Bites",
    price: 11.99,
    image: "https://images.unsplash.com/photo-1543852786-1cf6624b9987?w=300",
    description: "Delicious salmon treats for cats.",
    animalType: "cat",
    category: "treats",
    subcategory: "fish",
    SKU: "TR3005",
    brand: "Ocean Delight",
  },
  {
    id: 26,
    name: "Seed Bell Treat",
    price: 6.99,
    image: "https://images.unsplash.com/photo-1516545595035-b494dd0161e4?w=300",
    description: "Hanging seed bell for birds.",
    animalType: "bird",
    category: "treats",
    subcategory: "hanging",
    SKU: "TR3006",
    brand: "Feather Fun",
  },
  {
    id: 27,
    name: "Joint Health Chews",
    price: 15.99,
    image: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=300",
    description: "Supports joint health for dogs.",
    animalType: "dog",
    category: "treats",
    subcategory: "health",
    SKU: "TR3007",
    brand: "Vital Joints",
  },
  {
    id: 28,
    name: "Crunchy Cat Treats",
    price: 7.49,
    image: "https://images.unsplash.com/photo-1574235664855-4c5a5d4a8b1c?w=300",
    description: "Crunchy treats for dental health.",
    animalType: "cat",
    category: "treats",
    subcategory: "dental",
    SKU: "TR3008",
    brand: "Crispy Cats",
  },
  {
    id: 29,
    name: "Honey Sticks",
    price: 8.49,
    image: "https://images.unsplash.com/photo-1472491235688-bdc81a6d63fa?w=300",
    description: "Sweet honey sticks for birds.",
    animalType: "bird",
    category: "treats",
    subcategory: "sweet",
    SKU: "TR3009",
    brand: "Sweet Beak",
  },
  {
    id: 30,
    name: "Calming Chews",
    price: 16.99,
    image: "https://images.unsplash.com/photo-1554692918-08fa0fdc9db3?w=300",
    description: "Helps reduce anxiety in dogs.",
    animalType: "dog",
    category: "treats",
    subcategory: "calming",
    SKU: "TR3010",
    brand: "Peaceful Paws",
  },

  // Toys category
  {
    id: 31,
    name: "Interactive Laser Toy",
    price: 14.99,
    image: "https://images.unsplash.com/photo-1533738363-b7f9aef128ce?w=300",
    description: "Fun and safe interactive toy for your cat.",
    animalType: "cat",
    category: "toys",
    subcategory: "interactive",
    SKU: "TY4001",
    brand: "Play Time",
  },
  {
    id: 32,
    name: "Durable Chew Toy",
    price: 16.99,
    image: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=300",
    description: "Durable chew toy for dogs.",
    animalType: "dog",
    category: "toys",
    subcategory: "chew",
    SKU: "TY4002",
    brand: "Tough Chew",
  },
  {
    id: 33,
    name: "Bird Mirror Toy",
    price: 11.99,
    image: "https://images.unsplash.com/photo-1551085255-e6b9537e0636?w=300",
    description: "Entertaining mirror toy for birds.",
    animalType: "bird",
    category: "toys",
    subcategory: "mirror",
    SKU: "TY4003",
    brand: "Feather Friends",
  },
  {
    id: 34,
    name: "Plush Squeaky Toy",
    price: 12.99,
    image: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=300",
    description: "Soft plush toy with squeaker for dogs.",
    animalType: "dog",
    category: "toys",
    subcategory: "plush",
    SKU: "TY4004",
    brand: "Squeaky Fun",
  },
  {
    id: 35,
    name: "Feather Wand Toy",
    price: 9.99,
    image: "https://images.unsplash.com/photo-1533738363-b7f9aef128ce?w=300",
    description: "Interactive feather wand for cats.",
    animalType: "cat",
    category: "toys",
    subcategory: "interactive",
    SKU: "TY4005",
    brand: "Cat Chase",
  },
  {
    id: 36,
    name: "Foraging Toy",
    price: 13.99,
    image: "https://images.unsplash.com/photo-1516545595035-b494dd0161e4?w=300",
    description: "Stimulating foraging toy for birds.",
    animalType: "bird",
    category: "toys",
    subcategory: "foraging",
    SKU: "TY4006",
    brand: "Smart Bird",
  },
  {
    id: 37,
    name: "Tennis Ball Set",
    price: 8.99,
    image: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=300",
    description: "Set of 3 tennis balls for fetch.",
    animalType: "dog",
    category: "toys",
    subcategory: "fetch",
    SKU: "TY4007",
    brand: "Fetch Masters",
  },
  {
    id: 38,
    name: "Cat Tunnel",
    price: 24.99,
    image: "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=300",
    description: "Collapsible play tunnel for cats.",
    animalType: "cat",
    category: "toys",
    subcategory: "tunnel",
    SKU: "TY4008",
    brand: "Hide & Seek",
  },
  {
    id: 39,
    name: "Wooden Perch",
    price: 15.99,
    image: "https://images.unsplash.com/photo-1578779668325-78eb208bfd78?w=300",
    description: "Natural wooden perch for birds.",
    animalType: "bird",
    category: "toys",
    subcategory: "perch",
    SKU: "TY4009",
    brand: "Natural Branch",
  },
  {
    id: 40,
    name: "Rope Tug Toy",
    price: 10.99,
    image: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=300",
    description: "Durable rope toy for tug-of-war.",
    animalType: "dog",
    category: "toys",
    subcategory: "tug",
    SKU: "TY4010",
    brand: "Tug Time",
  },

  // Additional items to reach 50
  {
    id: 41,
    name: "Automatic Water Fountain",
    price: 34.99,
    image: "https://images.unsplash.com/photo-1576239312917-259a6a36cf6d?w=300",
    description: "Keeps water fresh and flowing.",
    animalType: "cat",
    category: "accessories",
    subcategory: "fountains",
    SKU: "AC2011",
    brand: "Fresh Flow",
  },
  {
    id: 42,
    name: "GPS Dog Tracker",
    price: 79.99,
    image: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=300",
    description: "Track your dog's location.",
    animalType: "dog",
    category: "accessories",
    subcategory: "trackers",
    SKU: "AC2012",
    brand: "Pet Safe",
  },
  {
    id: 43,
    name: "Nail Clipper Set",
    price: 14.99,
    image: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=300",
    description: "Professional pet nail clippers.",
    animalType: "dog",
    category: "accessories",
    subcategory: "grooming",
    SKU: "AC2013",
    brand: "Groom Pro",
  },
  {
    id: 44,
    name: "Window Perch",
    price: 29.99,
    image: "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=300",
    description: "Suction cup window perch for cats.",
    animalType: "cat",
    category: "accessories",
    subcategory: "furniture",
    SKU: "AC2014",
    brand: "Window Watch",
  },
  {
    id: 45,
    name: "Travel Water Bowl",
    price: 9.99,
    image: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=300",
    description: "Collapsible travel water bowl.",
    animalType: "dog",
    category: "accessories",
    subcategory: "bowls",
    SKU: "AC2015",
    brand: "Travel Buddy",
  },
  {
    id: 46,
    name: "Feather Teaser",
    price: 7.99,
    image: "https://images.unsplash.com/photo-1533738363-b7f9aef128ce?w=300",
    description: "Interactive feather teaser toy.",
    animalType: "cat",
    category: "toys",
    subcategory: "interactive",
    SKU: "TY4011",
    brand: "Playful Paws",
  },
  {
    id: 47,
    name: "Floating Perch",
    price: 18.99,
    image: "https://images.unsplash.com/photo-1578779668325-78eb208bfd78?w=300",
    description: "Floating perch for bird baths.",
    animalType: "bird",
    category: "accessories",
    subcategory: "baths",
    SKU: "AC2016",
    brand: "Aqua Birds",
  },
  {
    id: 48,
    name: "Dental Water Additive",
    price: 12.99,
    image: "https://images.unsplash.com/photo-1576239312917-259a6a36cf6d?w=300",
    description: "Promotes dental health in water.",
    animalType: "dog",
    category: "health",
    subcategory: "dental",
    SKU: "HL5001",
    brand: "Healthy Mouth",
  },
  {
    id: 49,
    name: "Cat Grass Kit",
    price: 15.99,
    image: "https://images.unsplash.com/photo-1592194996308-7b43878e84a6?w=300",
    description: "Growing kit for cat grass.",
    animalType: "cat",
    category: "food",
    subcategory: "grass",
    SKU: "PF1011",
    brand: "Green Paws",
  },
  {
    id: 50,
    name: "Nesting Material",
    price: 8.99,
    image: "https://images.unsplash.com/photo-1516545595035-b494dd0161e4?w=300",
    description: "Soft nesting material for birds.",
    animalType: "bird",
    category: "accessories",
    subcategory: "nesting",
    SKU: "AC2017",
    brand: "Cozy Nest",
  },
];
